version: "3.7"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "80:8080"
    depends_on:
      - db
      - migrations
    links:
      - db
  db:
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    image: "postgres:11.5"
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./db/pgdata:/pgdata
  migrations:
    build:
      context: ./migrations
      dockerfile: Dockerfile-migrations
    command: > 
      bash -c "go run . init
               go run ."
    depends_on:
      - db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
    links:
      - db
      