version: "3"
services:
  db:
    image: "postgres:11.5"
    ports:
      - "5432"
    volumes:
      - ./db/pgdata:/pgdata
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: glennmeyer/go_tutorial:latest
    ports: 
      - "80:8080"
    depends_on:
      - db
    links:
      - db
      